name: Build

on:
  push:
    branches:
      - build

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      node-version: 12.x
      expo-sdk-version: 36.0.0

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.node-version }}

      - name: Install packages
        run: yarn --frozen-lockfile

      - name: Link monorepo
        run: yarn f expo-link

      - name: Build Android
        if: runner.os == 'Linux'
        id: expo-build
        uses: nzws/turtle-action@master
        with:
          build-os: 'android'
          expo-sdk-version: ${{ env.expo-sdk-version }}
          working-dir: './packages/frontend/'
        env:
          EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
          EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}
          EXPO_ANDROID_KEYSTORE_BASE64: ${{ secrets.EXPO_ANDROID_KEYSTORE_BASE64 }}
          EXPO_ANDROID_KEYSTORE_ALIAS: ${{ secrets.EXPO_ANDROID_KEYSTORE_ALIAS }}
          EXPO_ANDROID_KEYSTORE_PASSWORD: ${{ secrets.EXPO_ANDROID_KEYSTORE_PASSWORD }}
          EXPO_ANDROID_KEY_PASSWORD: ${{ secrets.EXPO_ANDROID_KEY_PASSWORD }}

      - name: Upload asset
        uses: actions/upload-artifact@v1
        with:
          name: asset
          path: ${{ steps.expo-build.outputs.asset-path }}
